# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: My thoughts
email: joshpyzer@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My thoughts on the world of web and front end development.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://joshpyzer.github.io/" # the base hostname & protocol for your site
twitter_username: joshpyzer
github_username:  joshpyzer

# Build settings
markdown: kramdown
